

export const MAIN_API_URL = 'MAIN_API_URL';
export const REQUEST_API_RESULT = 'REQUEST_API_RESULT';
export const RECEIVE_API_RESULT = 'RECEIVE_API_RESULT';
export const REQUEST_API_RESULT_NEED_NAME = 'REQUEST_API_RESULT_NEED_NAME';
export const REQUEST_API_RESULT_WAS_LOAD = 'REQUEST_API_RESULT_WAS_LOAD';